# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphics_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(476, 418)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.checkBoxAntiAliasing = QtWidgets.QCheckBox(Dialog)
        self.checkBoxAntiAliasing.setObjectName("checkBoxAntiAliasing")
        self.verticalLayout.addWidget(self.checkBoxAntiAliasing)
        self.checkBoxShadows = QtWidgets.QCheckBox(Dialog)
        self.checkBoxShadows.setObjectName("checkBoxShadows")
        self.verticalLayout.addWidget(self.checkBoxShadows)
        self.checkBoxHighTextures = QtWidgets.QCheckBox(Dialog)
        self.checkBoxHighTextures.setObjectName("checkBoxHighTextures")
        self.verticalLayout.addWidget(self.checkBoxHighTextures)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonApply = QtWidgets.QPushButton(Dialog)
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.horizontalLayout.addWidget(self.pushButtonApply)
        self.pushButtonBack = QtWidgets.QPushButton(Dialog)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout.addWidget(self.pushButtonBack)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">GRAPHICS</span></p></body></html>"))
        self.checkBoxAntiAliasing.setText(_translate("Dialog", "ANTI ALIASING"))
        self.checkBoxShadows.setText(_translate("Dialog", "SHADOWS"))
        self.checkBoxHighTextures.setText(_translate("Dialog", "HIGH TEXTURES"))
        self.pushButtonApply.setText(_translate("Dialog", "APPLY"))
        self.pushButtonBack.setText(_translate("Dialog", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
