# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keybinds_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(523, 414)
        self.labelKeyBindsTitle = QtWidgets.QLabel(Dialog)
        self.labelKeyBindsTitle.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.labelKeyBindsTitle.setObjectName("labelKeyBindsTitle")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(100, 100, 331, 161))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelJumpKey = QtWidgets.QLabel(self.widget)
        self.labelJumpKey.setObjectName("labelJumpKey")
        self.horizontalLayout_3.addWidget(self.labelJumpKey)
        self.lineEditJumpKey = QtWidgets.QLineEdit(self.widget)
        self.lineEditJumpKey.setObjectName("lineEditJumpKey")
        self.horizontalLayout_3.addWidget(self.lineEditJumpKey)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelRunKey = QtWidgets.QLabel(self.widget)
        self.labelRunKey.setObjectName("labelRunKey")
        self.horizontalLayout_2.addWidget(self.labelRunKey)
        self.lineEditRunKey = QtWidgets.QLineEdit(self.widget)
        self.lineEditRunKey.setObjectName("lineEditRunKey")
        self.horizontalLayout_2.addWidget(self.lineEditRunKey)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelAttackKey = QtWidgets.QLabel(self.widget)
        self.labelAttackKey.setObjectName("labelAttackKey")
        self.horizontalLayout.addWidget(self.labelAttackKey)
        self.lineEditAttackKey = QtWidgets.QLineEdit(self.widget)
        self.lineEditAttackKey.setObjectName("lineEditAttackKey")
        self.horizontalLayout.addWidget(self.lineEditAttackKey)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(100, 320, 331, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonApply = QtWidgets.QPushButton(self.widget1)
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.horizontalLayout_4.addWidget(self.pushButtonApply)
        self.pushButtonBack = QtWidgets.QPushButton(self.widget1)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout_4.addWidget(self.pushButtonBack)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelKeyBindsTitle.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">KEY BINDINGS</span></p></body></html>"))
        self.labelJumpKey.setText(_translate("Dialog", "JUMP KEY"))
        self.labelRunKey.setText(_translate("Dialog", "RUN KEY"))
        self.labelAttackKey.setText(_translate("Dialog", "ATTACK KEY"))
        self.pushButtonApply.setText(_translate("Dialog", "APPLY"))
        self.pushButtonBack.setText(_translate("Dialog", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
